name:                gabelisp
version:             0.1.0.0
github:              "githubuser/gabelisp"
license:             BSD3
author:              "GTorello"
maintainer:          "gabriel128@gmail.com"
copyright:           "2019 Me"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gabelisp#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5 && < 0.7
- directory >= 1.2 && < 1.4
- haskeline >= 0.7 && < 0.8
- mtl >= 2.2 && < 2.3
- optparse-applicative >= 0.12.1 && < 0.15
- parsec >= 3.1 && < 3.2
- text >= 1.2 && < 1.3
- transformers >= 0.4 && < 0.6
- HTTP -any

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  gabelisp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -fno-warn-unused-do-bind
    - -fno-warn-unused-binds
    - -fno-warn-type-defaults
    - -fno-warn-type-defaults
    - -fno-warn-name-shadowing

    - -fwarn-duplicate-exports
    - -fwarn-dodgy-exports
    - -fwarn-dodgy-imports
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-record-updates
    - -fwarn-missing-fields
    - -fwarn-missing-methods
    - -fwarn-orphans
    - -fwarn-overlapping-patterns
    - -fwarn-unused-imports
    - -fwarn-tabs
    - -fwarn-unrecognised-pragmas
    dependencies:
    - gabelisp

tests:
  gabelisp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gabelisp
